### ISSUE TITLE
Add support for TOML configuration file in the user's home directory

### ISSUE THREAD

**Issue by tasbi03** [MadhurSaluja/Code-Complexity-Pro#10]
**Description**:

Currently, the program requires users to pass all configuration options as command-line arguments every time they run the tool. To improve usability, I propose adding support for a TOML configuration file that users can store in their home directory. This would allow the program to load default options from the configuration file, reducing the need to pass them via the command line.

### Task:

- Add support for reading a TOML configuration file named `.Code-complexity-pro-config.toml` from the user's home directory (e.g., `~/.Code-complexity-pro-config.toml`).
- If the configuration file exists, load the following options from it:
  - **model**: Specifies the model to use.
  - **api_key**: Specifies the API key for authentication.
  
- If any of the specified options are provided via command-line arguments, those should override the corresponding values from the TOML file.
  
- The program should ignore any unrecognized options in the config file.
  
- If the TOML file cannot be parsed (e.g., invalid format), the program should output an error message and exit.

###Error Handling:
- If the config file is missing, the program should proceed using defaults or command-line arguments.
- If the config file exists but cannot be parsed as valid TOML, the program should print an error message to stderr and exit.

**Comment by MadhurSaluja** [comment]
Checked the PR , Code works with TOML config.
